version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "root"
    working_dir: /app
    volumes:
      - ./server/:/app
    command: ash -c "npm i && node index.js"
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    command: ["nginx", "-g", "daemon off;"]
